print()
x1 = int(input("Enter x1 coordinate: "))
y1 = int(input("Enter y1 coordinate: "))
x2 = int(input("Enter x2 coordinate: "))
y2 = int(input("Enter y2 coordinate: "))

distance = (pow((x2-x1), 2)+pow((y2-y1), 2)) ** (1/2)
print()
print("Distance between (", str(x1), ", ", str(y1), ") and (", str(x2), ", ", str(y2), ") is: ", str(round(distance, 2)))
print()